### ISSUE TITLE
Error 401 : Unauthorised

### ISSUE THREAD

**Issue by immandala** [felipetodev/colabot#2]
Hey devs,
I really appreciate the effort and the work, like it is bang on. But recently, I encontered a status error 401 : Unauthorized when I tried to use ColaBot. Whenever I press Ctrl+Shift+I, this error pops up. Any fixes?

**Comment by felipetodev** [comment]
Hi @immandala !

I'm glad you're using our extension. Which provider are you using?

We will solve the problem and add other providers within the next few days.

**Comment by immandala** [comment]
I use OpenAI

**Comment by felipetodev** [comment]
We've added new OpenAI models and fixed some bugs.

Could we try our new version 1.9.0? 💯
